# Generated by Django 5.2.8 on 2025-11-27 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('calculation', 'Calculation'), ('plotting', 'Plotting'), ('financial_simple_interest', 'Financial Simple Interest'), ('financial_compound_interest', 'Financial Compound Interest')], max_length=50)),
                ('expression', models.TextField()),
                ('result', models.TextField()),
                ('variable_used', models.CharField(blank=True, max_length=10, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error')], default='success', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='calc_operat_user_id_b72504_idx'), models.Index(fields=['operation_type'], name='calc_operat_operati_b9a6d4_idx')],
            },
        ),
    ]
